development:
  adapter: postgresql
  encoding: unicode
  database: transaction_development
  pool: 5
  username: jesus
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: transaction_test
  pool: 5
  username: jesus
  password:
