development:
  adapter: postgresql
  encoding: unicode
  database: transaction_development
  pool: 5
  username: jesus
  password:

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
#test:
#  adapter: postgresql
#  encoding: unicode
#  database: transaction_test
#  pool: 5
#  username: jesus
#  password:
